// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks/contract.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/loloneme/potential-waffle/internal/infrastructure/persistence/models"
	gomock "go.uber.org/mock/gomock"
)

// MockcreatePRService is a mock of createPRService interface.
type MockcreatePRService struct {
	ctrl     *gomock.Controller
	recorder *MockcreatePRServiceMockRecorder
	isgomock struct{}
}

// MockcreatePRServiceMockRecorder is the mock recorder for MockcreatePRService.
type MockcreatePRServiceMockRecorder struct {
	mock *MockcreatePRService
}

// NewMockcreatePRService creates a new mock instance.
func NewMockcreatePRService(ctrl *gomock.Controller) *MockcreatePRService {
	mock := &MockcreatePRService{ctrl: ctrl}
	mock.recorder = &MockcreatePRServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcreatePRService) EXPECT() *MockcreatePRServiceMockRecorder {
	return m.recorder
}

// CreatePR mocks base method.
func (m *MockcreatePRService) CreatePR(ctx context.Context, pr *models.PullRequest) (models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePR", ctx, pr)
	ret0, _ := ret[0].(models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePR indicates an expected call of CreatePR.
func (mr *MockcreatePRServiceMockRecorder) CreatePR(ctx, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePR", reflect.TypeOf((*MockcreatePRService)(nil).CreatePR), ctx, pr)
}
