// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks/contract.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/loloneme/potential-waffle/internal/infrastructure/persistence/models"
	gomock "go.uber.org/mock/gomock"
)

// MockreassignPRService is a mock of reassignPRService interface.
type MockreassignPRService struct {
	ctrl     *gomock.Controller
	recorder *MockreassignPRServiceMockRecorder
	isgomock struct{}
}

// MockreassignPRServiceMockRecorder is the mock recorder for MockreassignPRService.
type MockreassignPRServiceMockRecorder struct {
	mock *MockreassignPRService
}

// NewMockreassignPRService creates a new mock instance.
func NewMockreassignPRService(ctrl *gomock.Controller) *MockreassignPRService {
	mock := &MockreassignPRService{ctrl: ctrl}
	mock.recorder = &MockreassignPRServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreassignPRService) EXPECT() *MockreassignPRServiceMockRecorder {
	return m.recorder
}

// ReassignReviewer mocks base method.
func (m *MockreassignPRService) ReassignReviewer(ctx context.Context, prID, oldReviewerID string) (models.PullRequest, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignReviewer", ctx, prID, oldReviewerID)
	ret0, _ := ret[0].(models.PullRequest)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReassignReviewer indicates an expected call of ReassignReviewer.
func (mr *MockreassignPRServiceMockRecorder) ReassignReviewer(ctx, prID, oldReviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignReviewer", reflect.TypeOf((*MockreassignPRService)(nil).ReassignReviewer), ctx, prID, oldReviewerID)
}
