// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks/contract.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sqlx "github.com/jmoiron/sqlx"
	models "github.com/loloneme/potential-waffle/internal/infrastructure/persistence/models"
	pull_request "github.com/loloneme/potential-waffle/internal/infrastructure/persistence/repository/pull_request"
	gomock "go.uber.org/mock/gomock"
)

// MockpullRequestRepository is a mock of pullRequestRepository interface.
type MockpullRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockpullRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockpullRequestRepositoryMockRecorder is the mock recorder for MockpullRequestRepository.
type MockpullRequestRepositoryMockRecorder struct {
	mock *MockpullRequestRepository
}

// NewMockpullRequestRepository creates a new mock instance.
func NewMockpullRequestRepository(ctrl *gomock.Controller) *MockpullRequestRepository {
	mock := &MockpullRequestRepository{ctrl: ctrl}
	mock.recorder = &MockpullRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpullRequestRepository) EXPECT() *MockpullRequestRepositoryMockRecorder {
	return m.recorder
}

// FindStatus mocks base method.
func (m *MockpullRequestRepository) FindStatus(ctx context.Context, spec pull_request.FindSpecification) (*models.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindStatus", ctx, spec)
	ret0, _ := ret[0].(*models.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindStatus indicates an expected call of FindStatus.
func (mr *MockpullRequestRepositoryMockRecorder) FindStatus(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindStatus", reflect.TypeOf((*MockpullRequestRepository)(nil).FindStatus), ctx, spec)
}

// GetAvailableReviewers mocks base method.
func (m *MockpullRequestRepository) GetAvailableReviewers(ctx context.Context, teamName string, excludeIDs []string, limit int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableReviewers", ctx, teamName, excludeIDs, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableReviewers indicates an expected call of GetAvailableReviewers.
func (mr *MockpullRequestRepositoryMockRecorder) GetAvailableReviewers(ctx, teamName, excludeIDs, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableReviewers", reflect.TypeOf((*MockpullRequestRepository)(nil).GetAvailableReviewers), ctx, teamName, excludeIDs, limit)
}

// GetPRByID mocks base method.
func (m *MockpullRequestRepository) GetPRByID(ctx context.Context, prID string) (models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRByID", ctx, prID)
	ret0, _ := ret[0].(models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRByID indicates an expected call of GetPRByID.
func (mr *MockpullRequestRepositoryMockRecorder) GetPRByID(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRByID", reflect.TypeOf((*MockpullRequestRepository)(nil).GetPRByID), ctx, prID)
}

// GetPullRequestReviewers mocks base method.
func (m *MockpullRequestRepository) GetPullRequestReviewers(ctx context.Context, prID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequestReviewers", ctx, prID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequestReviewers indicates an expected call of GetPullRequestReviewers.
func (mr *MockpullRequestRepositoryMockRecorder) GetPullRequestReviewers(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequestReviewers", reflect.TypeOf((*MockpullRequestRepository)(nil).GetPullRequestReviewers), ctx, prID)
}

// InsertPullRequest mocks base method.
func (m *MockpullRequestRepository) InsertPullRequest(ctx context.Context, tx *sqlx.Tx, pr *models.PullRequest) (models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPullRequest", ctx, tx, pr)
	ret0, _ := ret[0].(models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertPullRequest indicates an expected call of InsertPullRequest.
func (mr *MockpullRequestRepositoryMockRecorder) InsertPullRequest(ctx, tx, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPullRequest", reflect.TypeOf((*MockpullRequestRepository)(nil).InsertPullRequest), ctx, tx, pr)
}

// InsertReviewers mocks base method.
func (m *MockpullRequestRepository) InsertReviewers(ctx context.Context, tx *sqlx.Tx, prID string, reviewers []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertReviewers", ctx, tx, prID, reviewers)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertReviewers indicates an expected call of InsertReviewers.
func (mr *MockpullRequestRepositoryMockRecorder) InsertReviewers(ctx, tx, prID, reviewers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertReviewers", reflect.TypeOf((*MockpullRequestRepository)(nil).InsertReviewers), ctx, tx, prID, reviewers)
}

// PullRequestExists mocks base method.
func (m *MockpullRequestRepository) PullRequestExists(ctx context.Context, prID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullRequestExists", ctx, prID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullRequestExists indicates an expected call of PullRequestExists.
func (mr *MockpullRequestRepositoryMockRecorder) PullRequestExists(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullRequestExists", reflect.TypeOf((*MockpullRequestRepository)(nil).PullRequestExists), ctx, prID)
}

// ReassignReviewer mocks base method.
func (m *MockpullRequestRepository) ReassignReviewer(ctx context.Context, tx *sqlx.Tx, prID, oldReviewerID, newReviewerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignReviewer", ctx, tx, prID, oldReviewerID, newReviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReassignReviewer indicates an expected call of ReassignReviewer.
func (mr *MockpullRequestRepositoryMockRecorder) ReassignReviewer(ctx, tx, prID, oldReviewerID, newReviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignReviewer", reflect.TypeOf((*MockpullRequestRepository)(nil).ReassignReviewer), ctx, tx, prID, oldReviewerID, newReviewerID)
}

// SetPullRequestStatus mocks base method.
func (m *MockpullRequestRepository) SetPullRequestStatus(ctx context.Context, prID, statusName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPullRequestStatus", ctx, prID, statusName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPullRequestStatus indicates an expected call of SetPullRequestStatus.
func (mr *MockpullRequestRepositoryMockRecorder) SetPullRequestStatus(ctx, prID, statusName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPullRequestStatus", reflect.TypeOf((*MockpullRequestRepository)(nil).SetPullRequestStatus), ctx, prID, statusName)
}

// UpdatePullRequest mocks base method.
func (m *MockpullRequestRepository) UpdatePullRequest(ctx context.Context, spec pull_request.UpdateSpecification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePullRequest", ctx, spec)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePullRequest indicates an expected call of UpdatePullRequest.
func (mr *MockpullRequestRepositoryMockRecorder) UpdatePullRequest(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePullRequest", reflect.TypeOf((*MockpullRequestRepository)(nil).UpdatePullRequest), ctx, spec)
}

// WithTx mocks base method.
func (m *MockpullRequestRepository) WithTx(ctx context.Context, fn func(context.Context, *sqlx.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockpullRequestRepositoryMockRecorder) WithTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockpullRequestRepository)(nil).WithTx), ctx, fn)
}
