// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks/contract.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sqlx "github.com/jmoiron/sqlx"
	models "github.com/loloneme/potential-waffle/internal/infrastructure/persistence/models"
	gomock "go.uber.org/mock/gomock"
)

// MockteamRepository is a mock of teamRepository interface.
type MockteamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockteamRepositoryMockRecorder
	isgomock struct{}
}

// MockteamRepositoryMockRecorder is the mock recorder for MockteamRepository.
type MockteamRepositoryMockRecorder struct {
	mock *MockteamRepository
}

// NewMockteamRepository creates a new mock instance.
func NewMockteamRepository(ctrl *gomock.Controller) *MockteamRepository {
	mock := &MockteamRepository{ctrl: ctrl}
	mock.recorder = &MockteamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamRepository) EXPECT() *MockteamRepositoryMockRecorder {
	return m.recorder
}

// CreateTeam mocks base method.
func (m *MockteamRepository) CreateTeam(ctx context.Context, tx *sqlx.Tx, team models.Team) (models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", ctx, tx, team)
	ret0, _ := ret[0].(models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockteamRepositoryMockRecorder) CreateTeam(ctx, tx, team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockteamRepository)(nil).CreateTeam), ctx, tx, team)
}

// FindTeamByID mocks base method.
func (m *MockteamRepository) FindTeamByID(ctx context.Context, teamName string) (models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTeamByID", ctx, teamName)
	ret0, _ := ret[0].(models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTeamByID indicates an expected call of FindTeamByID.
func (mr *MockteamRepositoryMockRecorder) FindTeamByID(ctx, teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTeamByID", reflect.TypeOf((*MockteamRepository)(nil).FindTeamByID), ctx, teamName)
}

// WithTx mocks base method.
func (m *MockteamRepository) WithTx(ctx context.Context, fn func(context.Context, *sqlx.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockteamRepositoryMockRecorder) WithTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockteamRepository)(nil).WithTx), ctx, fn)
}
