// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks/contract.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/loloneme/potential-waffle/internal/infrastructure/persistence/models"
	gomock "go.uber.org/mock/gomock"
)

// MockcreateTeamService is a mock of createTeamService interface.
type MockcreateTeamService struct {
	ctrl     *gomock.Controller
	recorder *MockcreateTeamServiceMockRecorder
	isgomock struct{}
}

// MockcreateTeamServiceMockRecorder is the mock recorder for MockcreateTeamService.
type MockcreateTeamServiceMockRecorder struct {
	mock *MockcreateTeamService
}

// NewMockcreateTeamService creates a new mock instance.
func NewMockcreateTeamService(ctrl *gomock.Controller) *MockcreateTeamService {
	mock := &MockcreateTeamService{ctrl: ctrl}
	mock.recorder = &MockcreateTeamServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcreateTeamService) EXPECT() *MockcreateTeamServiceMockRecorder {
	return m.recorder
}

// CreateTeam mocks base method.
func (m *MockcreateTeamService) CreateTeam(ctx context.Context, team *models.Team) (models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", ctx, team)
	ret0, _ := ret[0].(models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockcreateTeamServiceMockRecorder) CreateTeam(ctx, team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockcreateTeamService)(nil).CreateTeam), ctx, team)
}
