// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks/contract.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/loloneme/potential-waffle/internal/infrastructure/persistence/models"
	gomock "go.uber.org/mock/gomock"
)

// MockMergePRService is a mock of MergePRService interface.
type MockMergePRService struct {
	ctrl     *gomock.Controller
	recorder *MockMergePRServiceMockRecorder
	isgomock struct{}
}

// MockMergePRServiceMockRecorder is the mock recorder for MockMergePRService.
type MockMergePRServiceMockRecorder struct {
	mock *MockMergePRService
}

// NewMockMergePRService creates a new mock instance.
func NewMockMergePRService(ctrl *gomock.Controller) *MockMergePRService {
	mock := &MockMergePRService{ctrl: ctrl}
	mock.recorder = &MockMergePRServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMergePRService) EXPECT() *MockMergePRServiceMockRecorder {
	return m.recorder
}

// MergePullRequest mocks base method.
func (m *MockMergePRService) MergePullRequest(ctx context.Context, prID, mergeStatus string) (models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePullRequest", ctx, prID, mergeStatus)
	ret0, _ := ret[0].(models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergePullRequest indicates an expected call of MergePullRequest.
func (mr *MockMergePRServiceMockRecorder) MergePullRequest(ctx, prID, mergeStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePullRequest", reflect.TypeOf((*MockMergePRService)(nil).MergePullRequest), ctx, prID, mergeStatus)
}
