// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks/contract.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/loloneme/potential-waffle/internal/infrastructure/persistence/models"
	pull_request "github.com/loloneme/potential-waffle/internal/infrastructure/persistence/repository/pull_request"
	gomock "go.uber.org/mock/gomock"
)

// MockprRepo is a mock of prRepo interface.
type MockprRepo struct {
	ctrl     *gomock.Controller
	recorder *MockprRepoMockRecorder
	isgomock struct{}
}

// MockprRepoMockRecorder is the mock recorder for MockprRepo.
type MockprRepoMockRecorder struct {
	mock *MockprRepo
}

// NewMockprRepo creates a new mock instance.
func NewMockprRepo(ctrl *gomock.Controller) *MockprRepo {
	mock := &MockprRepo{ctrl: ctrl}
	mock.recorder = &MockprRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprRepo) EXPECT() *MockprRepoMockRecorder {
	return m.recorder
}

// FindPullRequests mocks base method.
func (m *MockprRepo) FindPullRequests(ctx context.Context, spec pull_request.FindSpecification) ([]models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPullRequests", ctx, spec)
	ret0, _ := ret[0].([]models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPullRequests indicates an expected call of FindPullRequests.
func (mr *MockprRepoMockRecorder) FindPullRequests(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPullRequests", reflect.TypeOf((*MockprRepo)(nil).FindPullRequests), ctx, spec)
}
