// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks/contract.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sqlx "github.com/jmoiron/sqlx"
	models "github.com/loloneme/potential-waffle/internal/infrastructure/persistence/models"
	user "github.com/loloneme/potential-waffle/internal/infrastructure/persistence/repository/user"
	gomock "go.uber.org/mock/gomock"
)

// MockuserRepository is a mock of userRepository interface.
type MockuserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepositoryMockRecorder
	isgomock struct{}
}

// MockuserRepositoryMockRecorder is the mock recorder for MockuserRepository.
type MockuserRepositoryMockRecorder struct {
	mock *MockuserRepository
}

// NewMockuserRepository creates a new mock instance.
func NewMockuserRepository(ctrl *gomock.Controller) *MockuserRepository {
	mock := &MockuserRepository{ctrl: ctrl}
	mock.recorder = &MockuserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepository) EXPECT() *MockuserRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockuserRepository) Find(ctx context.Context, spec user.FindSpecification) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, spec)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockuserRepositoryMockRecorder) Find(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockuserRepository)(nil).Find), ctx, spec)
}

// GetUserByID mocks base method.
func (m *MockuserRepository) GetUserByID(ctx context.Context, userID string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockuserRepositoryMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockuserRepository)(nil).GetUserByID), ctx, userID)
}

// GetUserTeamName mocks base method.
func (m *MockuserRepository) GetUserTeamName(ctx context.Context, userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTeamName", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTeamName indicates an expected call of GetUserTeamName.
func (mr *MockuserRepositoryMockRecorder) GetUserTeamName(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTeamName", reflect.TypeOf((*MockuserRepository)(nil).GetUserTeamName), ctx, userID)
}

// UpsertUsers mocks base method.
func (m *MockuserRepository) UpsertUsers(ctx context.Context, tx *sqlx.Tx, users []models.User) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUsers", ctx, tx, users)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUsers indicates an expected call of UpsertUsers.
func (mr *MockuserRepositoryMockRecorder) UpsertUsers(ctx, tx, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUsers", reflect.TypeOf((*MockuserRepository)(nil).UpsertUsers), ctx, tx, users)
}

// UserUpdate mocks base method.
func (m *MockuserRepository) UserUpdate(ctx context.Context, spec user.UpdateSpecification) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserUpdate", ctx, spec)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserUpdate indicates an expected call of UserUpdate.
func (mr *MockuserRepositoryMockRecorder) UserUpdate(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserUpdate", reflect.TypeOf((*MockuserRepository)(nil).UserUpdate), ctx, spec)
}
