// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks/contract.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/loloneme/potential-waffle/internal/infrastructure/persistence/models"
	user "github.com/loloneme/potential-waffle/internal/infrastructure/persistence/repository/user"
	gomock "go.uber.org/mock/gomock"
)

// MockuserRepo is a mock of userRepo interface.
type MockuserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepoMockRecorder
	isgomock struct{}
}

// MockuserRepoMockRecorder is the mock recorder for MockuserRepo.
type MockuserRepoMockRecorder struct {
	mock *MockuserRepo
}

// NewMockuserRepo creates a new mock instance.
func NewMockuserRepo(ctrl *gomock.Controller) *MockuserRepo {
	mock := &MockuserRepo{ctrl: ctrl}
	mock.recorder = &MockuserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepo) EXPECT() *MockuserRepoMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockuserRepo) Find(ctx context.Context, spec user.FindSpecification) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, spec)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockuserRepoMockRecorder) Find(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockuserRepo)(nil).Find), ctx, spec)
}

// MockteamRepo is a mock of teamRepo interface.
type MockteamRepo struct {
	ctrl     *gomock.Controller
	recorder *MockteamRepoMockRecorder
	isgomock struct{}
}

// MockteamRepoMockRecorder is the mock recorder for MockteamRepo.
type MockteamRepoMockRecorder struct {
	mock *MockteamRepo
}

// NewMockteamRepo creates a new mock instance.
func NewMockteamRepo(ctrl *gomock.Controller) *MockteamRepo {
	mock := &MockteamRepo{ctrl: ctrl}
	mock.recorder = &MockteamRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamRepo) EXPECT() *MockteamRepoMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockteamRepo) Exists(ctx context.Context, teamName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, teamName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockteamRepoMockRecorder) Exists(ctx, teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockteamRepo)(nil).Exists), ctx, teamName)
}
